---
language: python

python:
  - 2.7

services:
  - docker

sudo: required

env:
  matrix:
    - os=centos version=6 container_id=$(mktemp) ANSIBLE_VERSION=latest
    - os=centos version=6 container_id=$(mktemp) ANSIBLE_VERSION=2.6.3
    - os=centos version=6 container_id=$(mktemp) ANSIBLE_VERSION=2.5.8
    - os=centos version=6 container_id=$(mktemp) ANSIBLE_VERSION=2.4.6
    - os=centos version=7 container_id=$(mktemp) ANSIBLE_VERSION=latest
    - os=centos version=7 container_id=$(mktemp) ANSIBLE_VERSION=2.6.3
    - os=centos version=7 container_id=$(mktemp) ANSIBLE_VERSION=2.5.8
    - os=centos version=7 container_id=$(mktemp) ANSIBLE_VERSION=2.4.6
    - os=debian version=jessie container_id=$(mktemp) ANSIBLE_VERSION=latest
    - os=debian version=jessie container_id=$(mktemp) ANSIBLE_VERSION=2.6.3
    - os=debian version=jessie container_id=$(mktemp) ANSIBLE_VERSION=2.5.8
    - os=debian version=jessie container_id=$(mktemp) ANSIBLE_VERSION=2.4.6
    - os=debian version=stretch container_id=$(mktemp) ANSIBLE_VERSION=latest
    - os=debian version=stretch container_id=$(mktemp) ANSIBLE_VERSION=2.6.3
    - os=debian version=stretch container_id=$(mktemp) ANSIBLE_VERSION=2.5.8
    - os=debian version=stretch container_id=$(mktemp) ANSIBLE_VERSION=2.4.6
    - os=ubuntu version=trusty container_id=$(mktemp) ANSIBLE_VERSION=latest
    - os=ubuntu version=trusty container_id=$(mktemp) ANSIBLE_VERSION=2.6.3
    - os=ubuntu version=trusty container_id=$(mktemp) ANSIBLE_VERSION=2.5.8
    - os=ubuntu version=trusty container_id=$(mktemp) ANSIBLE_VERSION=2.4.6
    - os=ubuntu version=xenial container_id=$(mktemp) ANSIBLE_VERSION=latest
    - os=ubuntu version=xenial container_id=$(mktemp) ANSIBLE_VERSION=2.6.3
    - os=ubuntu version=xenial container_id=$(mktemp) ANSIBLE_VERSION=2.5.8
    - os=ubuntu version=xenial container_id=$(mktemp) ANSIBLE_VERSION=2.4.6
    - os=ubuntu version=bionic container_id=$(mktemp) ANSIBLE_VERSION=latest
    - os=ubuntu version=bionic container_id=$(mktemp) ANSIBLE_VERSION=2.6.3
    - os=ubuntu version=bionic container_id=$(mktemp) ANSIBLE_VERSION=2.5.8
    - os=ubuntu version=bionic container_id=$(mktemp) ANSIBLE_VERSION=2.4.6

install:
  - if [ "${ANSIBLE_VERSION}" = "latest" ]; then sudo pip install ansible; else sudo pip install ansible==${ANSIBLE_VERSION}; fi
  - docker pull ${os}:${version}
  - sudo docker build --file tests/Docker/Dockerfile.${os}_${version} --tag=${os}${version} tests/Docker

script:
  - docker run --privileged -d --name target.host ${os}${version} /sbin/init > "${container_id}"

  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory | grep -q 'changed=0.*failed=0' && (echo "" && exit 0) || (echo 'Changed or failed after retry' && exit 1)


  - 'sudo docker exec -t "$(cat ${container_id})" cat /etc/motd | grep "xx      xx  xxxxxx  xxxxxx  xxxx"; if [ $? -ne 0 ]; then exit 1; fi'
  - 'sudo docker exec -t "$(cat ${container_id})" cat /etc/motd | grep "xxxx  xxxx  xx  xx    xx    xx  xx"; if [ $? -ne 0 ]; then exit 1; fi'
  - 'sudo docker exec -t "$(cat ${container_id})" cat /etc/motd | grep "xx xxxx xx  xx  xx    xx    xx  xx"; if [ $? -ne 0 ]; then exit 1; fi'
  - 'sudo docker exec -t "$(cat ${container_id})" cat /etc/motd | grep "xx  xx  xx  xxxxxx    xx    xxxx"; if [ $? -ne 0 ]; then exit 1; fi'
  - 'sudo docker exec -t "$(cat ${container_id})" cat /etc/motd | grep "author: shhirose"; if [ $? -ne 0 ]; then exit 1; fi'
  - 'sudo docker exec -t "$(cat ${container_id})" cat /etc/motd | grep "git: https://github.com/shhirose/ansible-motd"; if [ $? -ne 0 ]; then exit 1; fi'
  - 'sudo docker exec -t "$(cat ${container_id})" cat /etc/motd | grep "ansible-galaxy: https://galaxy.ansible.com/shhirose/motd/"; if [ $? -ne 0 ]; then exit 1; fi'

after_script:
  - sudo docker stop "$(cat ${container_id})"

  - sudo docker rm "$(cat ${container_id})"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
